development:
  adapter: postgresql
  encoding: unicode
  database: myarticles
  pool: 5
  username: fahad
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: myarticles
  pool: 5
  username: fahad
  password: 123